services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
  backend:
    build: .
    restart: always
    ports:
      - 9000:3000
    environment:
      - KAKAO_RESTAPI_KEY=${KAKAO_RESTAPI_KEY}
      - SESSION_SECRET=${SESSION_SECRET}
      - MONGO_URL=mongodb://root:${MONGO_ROOT_PASSWORD}@localhost:27017/gift-fund?authSource=admin
